### ISSUE TITLE
Install problem

### ISSUE THREAD

**Issue by devilboys** [jtagt/mee6#11]
Can i run this on pc using window os ? if yes , is there any tutorial to install it ?

**Comment by SilBoydens** [comment]
Either use wsl or a virtual machine. 

NOTE: this is not for anyone to set up, some computer knowledge is required

**Comment by laggycomputer** [comment]
This installation only works on Debian-based Linux distributions. If you run Windows, a VM or WSL would be a good idea. Like Sil said, some computer knowledge required.

**Comment by jtagt** [comment]
ehh might work never tried it though.

**Comment by SilBoydens** [comment]
wut? no

just use compose and a .env file
don't make it hard, make it easy

**Comment by jtagt** [comment]
But when I use the .env it doesn't work. It looks as if it is pulling from the os itself.

**Comment by jtagt** [comment]
Instead, you could just set the variables via the app.py just to make it a little easier.

**Comment by SilBoydens** [comment]
-_- do you even docker mate?

you need to say IN THE DOCKER COMPOSE file that it has to take that .env file
and there are a lot of diffrent places where you would have to set the same variables again and again

**Comment by jtagt** [comment]
@devilboy26 There is a docker-compose file so if you would like to self-host on windows it is pretty similar to windows. I will be creating a guide to windows sometime in the feature.

**Comment by SilBoydens** [comment]
The one I added is NOT complete, I don't know if you updated it already
________________________________

**Comment by devilboy26** [comment]
Can you make a guide show me how to set it up?

**Comment by laggycomputer** [comment]
@devilboy26 As stated above, the guide remains incomplete.

**Comment by devilboy26** [comment]
Ok thank

**Comment by laggycomputer** [comment]
lol, @SilBoydens... I forgot what WSL is. Now I remember...
WSL isn't the best route, here's why...
'sources.list' on Debian based distros using WSL (we assume we're using Ubuntu in the guide) don't have 'universe' or 'multiverse' enabled, and often have the wrong versions in 'sources.list'. I found that my Ubuntu 18.04 using WSL had 'xenial' (Ubuntu 18.04 should be 'bionic') as the version in 'sources.list', and didn't have 'universe' or 'multiverse' enabled.
