### ISSUE TITLE
"bg" in README.md

### ISSUE THREAD

**Issue by laggycomputer** [jtagt/mee6#12]
Shouldn't we be adding '&' at the end of our python run commands instead of running 'bg' after?

**Comment by laggycomputer** [comment]
Btw... no need to 'chmod' the install.sh before running... we're using root in the first place.

**Comment by jtagt** [comment]
No, we’ll be switching to docker eventually I just don’t have time to attempt to make one. Although sil made one 🤔. And yes you have to run chmod to make it executable.

**Comment by laggycomputer** [comment]
hmmmmm... really... if root cloned the repo, shouldn't root already have permissions? i never had to run chmod when I set mine up...

**Comment by SilBoydens** [comment]
Depends on how you start it.
`sh ./install.sh` does not require chmod
`./install.sh` will require chmod

**Comment by jtagt** [comment]
I have always used ``./install.sh`` so ill change the guide just so there aren't as many steps.

**Comment by SilBoydens** [comment]
note: sh does not work on all linux systems, sometimes you need to use bash ./install.sh

**Comment by jtagt** [comment]
Imma just assume that they use Ubuntu

**Comment by laggycomputer** [comment]
Yeah... we're already doing that so its all good. Watch out they might have change sh to a symlink to ash or something, even though that's really rare. Still, not too important of an issue. Go ahead and close this thing.
