### ISSUE TITLE
backdoor.py?

### ISSUE THREAD

**Issue by Winter145** [jtagt/mee6#15]
I was just looking through the source, and I just see backdoor.py. What is the purpose of this file, and is it malicious?

**Comment by laggycomputer** [comment]
This file was added by the upstream repository for what seems to be an asyncio workaround.

Our support server exists, issues are not the place for "what does x do" questions.

**Comment by laggycomputer** [comment]
(also, if we really wanted to compromise something, we would hide it in other files and disguise it as something else, not openly call it backdoor.py and leave a default commit message :D)

**Comment by Winter145** [comment]
Okay lol, I just wanted to make sure it was nothing malicious
