### ISSUE TITLE
Requiring re authentication after every action

### ISSUE THREAD

**Issue by fdizile** [jtagt/mee6#2]
Takes me back to the oauth page when I attempt to enable any plugins.

No clue why.

**Comment by fdizile** [comment]
@jtagt

**Comment by jtagt** [comment]
Is this occurring when you go to the dashboard?

**Comment by fdizile** [comment]
Not when you go to, but when you perform an action.

https://i.imgur.com/W2d9Zul.gifv

**Comment by jtagt** [comment]
Seems like its having an issue corresponding to the bot... Did you start the bot correct?

**Comment by fdizile** [comment]
Just figured it out. Hadn't started the bot, period.

Great stuff man, keep it up.

**Comment by jtagt** [comment]
@fdizile No problem glad it worked!
